#!/usr/bin/env bash
#
# One command to bring the whole stack up, first run or hundredth.
#
#   pnpm docker:start
#
# It is idempotent by design. The only genuinely dangerous step is seeding, so
# that runs if and only if the database has no users yet — an already-populated
# database is never touched, no matter how many times this is run.
#
# Written for bash 3.2, which is what macOS ships. No associative arrays, no
# ${var,,}, nothing from bash 4.

set -euo pipefail

cd "$(dirname "$0")/.."

# Compose builds container and volume names from the project name, which it
# takes from the directory. Both the port check and the pgdata guard need it.
PROJECT=$(basename "$PWD" | tr '[:upper:]' '[:lower:]' | tr -cd 'a-z0-9_-')

# Colour only when attached to a terminal, so CI logs stay clean.
if [ -t 1 ]; then
  R=$'\033[31m'; G=$'\033[32m'; Y=$'\033[33m'; B=$'\033[1m'; X=$'\033[0m'
else
  R=''; G=''; Y=''; B=''; X=''
fi

step() { printf '\n%s==>%s %s%s%s\n' "$B" "$X" "$B" "$1" "$X"; }
ok()   { printf '    %s✓%s %s\n' "$G" "$X" "$1"; }
warn() { printf '    %s!%s %s\n' "$Y" "$X" "$1"; }
die()  { printf '\n%sError:%s %s\n\n' "$R" "$X" "$1" >&2; exit 1; }

# ---------------------------------------------------------------- preflight --

step "Checking prerequisites"

command -v docker >/dev/null 2>&1 \
  || die "Docker is not installed.
  macOS:  https://docs.docker.com/desktop/install/mac-install/
  Linux:  https://docs.docker.com/engine/install/"

docker info >/dev/null 2>&1 \
  || die "Docker is installed but not running. Start Docker Desktop (or 'sudo systemctl start docker') and try again."

docker compose version >/dev/null 2>&1 \
  || die "The Docker Compose plugin is missing. Install it: https://docs.docker.com/compose/install/"

ok "docker $(docker version --format '{{.Server.Version}}' 2>/dev/null || echo '?')"

# The published-port check lives further down, in "Checking ports" — it needs
# HOST_PORT, which is not known until the env file has been resolved.

# ---------------------------------------------------------- environment file --

step "Checking environment"

# The Makefile uses the same rule: .env.docker if present, else .env.
if [ -f .env.docker ]; then
  ENV_FILE=.env.docker
elif [ -f .env ]; then
  ENV_FILE=.env
else
  ENV_FILE=""
fi

read_var() { # read_var FILE NAME -> value, or empty
  [ -f "$1" ] || return 0
  sed -n "s/^$2=//p" "$1" | head -1 | tr -d '\r'
}

# A .env aimed at Homebrew Postgres cannot drive Compose: the DB host there is
# localhost, which inside a container means the container itself. Rather than
# edit the file `pnpm dev` depends on, generate a Docker-specific one.
needs_docker_env=0
if [ -z "$ENV_FILE" ]; then
  needs_docker_env=1
elif [ "$ENV_FILE" = ".env" ]; then
  case "$(read_var .env DATABASE_URI)" in
    *@postgres:*) : ;;              # already Compose-shaped, e.g. a server
    *) needs_docker_env=1 ;;
  esac
fi

if [ "$needs_docker_env" = "1" ]; then
  command -v openssl >/dev/null 2>&1 || die "openssl is needed to generate secrets but was not found."

  # Postgres stores the password it was created with inside its data volume and
  # never re-reads POSTGRES_PASSWORD. Generating a fresh password while that
  # volume still exists produces an authentication failure several steps later
  # that looks nothing like its cause, so stop here instead.
  if docker volume inspect "${PROJECT}_pgdata" >/dev/null 2>&1; then
    die "A database volume (${PROJECT}_pgdata) already exists, but there is no env
  file to go with it. Generating a new password now would not match the one
  baked into that volume, and every query would fail to authenticate.

  Either restore the .env.docker that created it, or discard the database:
    docker volume rm ${PROJECT}_pgdata     # deletes all content, no undo"
  fi

  warn "No Compose-ready env file found — creating .env.docker"

  PGPW=$(openssl rand -hex 16)
  {
    echo "# Generated by pnpm docker:start. Used by the Docker stack only;"
    echo "# .env is left alone so 'pnpm dev' keeps working against Homebrew Postgres."
    echo "ENV_FILE=.env.docker"
    echo
    echo "DATABASE_URI=postgres://sustlabs:${PGPW}@postgres:5432/sustlabs_cms"
    echo "POSTGRES_PASSWORD=${PGPW}"
    echo "PAYLOAD_SECRET=$(openssl rand -hex 32)"
    echo "PREVIEW_SECRET=$(openssl rand -hex 16)"
    echo "NEXT_PUBLIC_SERVER_URL=http://localhost:3000"
    echo
    echo "# Host side of the published port. The container always listens on"
    echo "# 3000; change this only when something else already holds the port."
    echo "HOST_PORT=3000"
    echo
    echo "# Blank -> the seed falls back to the defaults in src/seed/users.ts."
    echo "SEED_PASSWORD_ASHISH="
    echo "SEED_PASSWORD_SHREYA="
    echo

    # Carry over anything non-secret already configured, so analytics and lead
    # forwarding behave the same as in local dev.
    for k in LEAD_FORWARD_ENDPOINT NEXT_PUBLIC_GA_MEASUREMENT_ID \
             NEXT_PUBLIC_GOOGLE_ADS_ID NEXT_PUBLIC_GTM_ID; do
      echo "${k}=$(read_var .env "$k")"
    done
    echo
    echo "# Uploads persist in Docker volumes, so S3 stays off."
    for k in S3_BUCKET S3_ACCESS_KEY_ID S3_SECRET_ACCESS_KEY S3_REGION S3_ENDPOINT; do
      echo "${k}="
    done
  } > .env.docker

  ENV_FILE=.env.docker
  ok "Created .env.docker with freshly generated secrets"

  # These defaults are fine on a laptop and wrong on a server, so say so loudly
  # rather than let a production build bake in a localhost URL.
  printf '\n%s  This generated file is for LOCAL development.%s\n' "$Y" "$X"
  printf '  On a production server, write .env by hand instead and set:\n'
  printf '    NEXT_PUBLIC_SERVER_URL=https://www.sustlabs.com   (inlined at\n'
  printf '      build time — a wrong value needs a full rebuild to correct)\n'
  printf '    SEED_PASSWORD_ASHISH / SEED_PASSWORD_SHREYA       (or the seed\n'
  printf '      uses the defaults committed in src/seed/users.ts)\n\n'
fi

ok "Using $ENV_FILE"

# Validate the two mistakes that produce the most confusing failures.
DB_URI=$(read_var "$ENV_FILE" DATABASE_URI)
PG_PW=$(read_var "$ENV_FILE" POSTGRES_PASSWORD)

[ -n "$DB_URI" ] || die "DATABASE_URI is not set in $ENV_FILE"
[ -n "$(read_var "$ENV_FILE" PAYLOAD_SECRET)" ] \
  || die "PAYLOAD_SECRET is not set in $ENV_FILE. Generate one: openssl rand -hex 32"

case "$DB_URI" in
  *@postgres:*) : ;;
  *) die "DATABASE_URI in $ENV_FILE points at '$(echo "$DB_URI" | sed 's|.*@||; s|/.*||')'.
  Inside Compose the database host is the service name 'postgres', not localhost:
    DATABASE_URI=postgres://sustlabs:<password>@postgres:5432/sustlabs_cms" ;;
esac

[ -n "$PG_PW" ] || die "POSTGRES_PASSWORD is not set in $ENV_FILE"

# Postgres is created with POSTGRES_PASSWORD on first boot and never re-reads
# it, so a mismatch here fails authentication in a way that looks like a bug.
URI_PW=$(echo "$DB_URI" | sed -n 's|^postgres://[^:]*:\([^@]*\)@.*|\1|p')
[ "$URI_PW" = "$PG_PW" ] \
  || die "The password inside DATABASE_URI does not match POSTGRES_PASSWORD in $ENV_FILE.
  They must be identical — Postgres bakes the password in on first boot."

ok "Environment looks consistent"

# ------------------------------------------------------------------- ports ---

step "Checking ports"

# Only the host side of the mapping is configurable. The container always
# listens on 3000, so the image, NEXT_PUBLIC_SERVER_URL and the internal
# hostname are all unaffected by this — the variable is deliberately not called
# PORT, because that name would be picked up by Next inside the container and
# move the listener too, leaving the mapping pointing at nothing.
#
# Set it when 3000 is already taken on the host: during a cutover from a legacy
# PM2 deployment, say, where the old process keeps serving until nginx is
# flipped. Whatever it is set to, nginx's proxy_pass must match.
#
# An exported HOST_PORT wins over the env file, which lets a one-off run
# override it:  HOST_PORT=3001 ./scripts/docker-start.sh
if [ -z "${HOST_PORT:-}" ]; then
  HOST_PORT=$(read_var "$ENV_FILE" HOST_PORT)
fi
HOST_PORT="${HOST_PORT:-3000}"

case "$HOST_PORT" in
  ''|*[!0-9]*) die "HOST_PORT must be a number, but is '$HOST_PORT'." ;;
esac

# Compose reads it from --env-file for the mapping, but exporting covers the
# case where it came from the environment rather than the file.
export HOST_PORT

# The port has to be free, or the app container will fail to publish it. Only
# complain if something *other* than our own container is holding it.
if lsof -nP -iTCP:"$HOST_PORT" -sTCP:LISTEN >/dev/null 2>&1; then
  if ! docker ps --format '{{.Names}}' | grep -q "^${PROJECT}-app-1$"; then
    die "Port $HOST_PORT is already in use by another process.
  Find it with:  sudo lsof -nP -iTCP:$HOST_PORT -sTCP:LISTEN
  Then stop it, or publish on a different port by setting HOST_PORT in
  $ENV_FILE — and point nginx's proxy_pass at the same port."
  fi
fi

ok "Publishing on 127.0.0.1:$HOST_PORT"

COMPOSE="docker compose --env-file $ENV_FILE"
export BUILDX_BUILDER=sustlabs-builder

# ------------------------------------------------------------ build plumbing --

step "Preparing build environment"

if docker network inspect sustlabs >/dev/null 2>&1; then
  ok "network 'sustlabs' present"
else
  docker network create sustlabs >/dev/null
  ok "network 'sustlabs' created"
fi

# The image build has to reach Postgres (every page is prerendered from the
# database), and BuildKit will not join a Compose network by itself. A builder
# attached to that network is what makes one DATABASE_URI work for both build
# and runtime.
if docker buildx inspect "$BUILDX_BUILDER" >/dev/null 2>&1; then
  ok "builder '$BUILDX_BUILDER' present"
else
  docker buildx create --name "$BUILDX_BUILDER" --driver docker-container \
    --driver-opt network=sustlabs \
    --buildkitd-flags '--allow-insecure-entitlement network.host' >/dev/null
  ok "builder '$BUILDX_BUILDER' created"
fi

# ---------------------------------------------------------------- database ---

step "Starting Postgres"

$COMPOSE up -d --wait postgres >/dev/null 2>&1 || {
  $COMPOSE logs --tail 30 postgres || true
  die "Postgres did not become healthy. Logs are above.
  A password change against an existing volume is the usual cause; the volume
  keeps the original password."
}
ok "Postgres healthy"

step "Applying migrations"

MIGRATE_LOG=$(mktemp)
if ! $COMPOSE run --rm migrate 2>&1 | tee "$MIGRATE_LOG"; then
  # Authentication failures here almost always mean the env file's password and
  # the one inside the existing data volume have diverged — worth naming,
  # because "migrations failed" sends people looking at the wrong thing.
  if grep -q "password authentication failed" "$MIGRATE_LOG"; then
    rm -f "$MIGRATE_LOG"
    die "Postgres rejected the password in $ENV_FILE.

  The database volume keeps the password it was first created with; changing
  POSTGRES_PASSWORD afterwards has no effect on it. Either put the original
  password back in $ENV_FILE, or start over:
    $COMPOSE down && docker volume rm $(basename "$PWD")_pgdata"
  fi
  rm -f "$MIGRATE_LOG"
  die "Migrations failed. Nothing else has been changed.
  Inspect with:  docker compose --env-file $ENV_FILE run --rm tools pnpm payload migrate:status"
fi
rm -f "$MIGRATE_LOG"
ok "Schema up to date"

# ------------------------------------------------------------------- seed ----

step "Checking content"

# Empty means the table is not there yet; a number means it is.
USER_COUNT=$($COMPOSE exec -T postgres \
  psql -U sustlabs -d sustlabs_cms -tAc "select count(*) from users" 2>/dev/null | tr -d '[:space:]' || true)

if [ -z "$USER_COUNT" ] || [ "$USER_COUNT" = "0" ]; then
  warn "Database is empty — seeding (first run only)"
  # The build prerenders every page from the database, so this has to happen
  # before the image is built or the build fails in generateStaticParams.
  $COMPOSE run --rm tools pnpm seed \
    || die "Seeding failed. Fix the cause and re-run; the seed skips anything already created."
  ok "Content seeded"
else
  ok "Content already present ($USER_COUNT users) — seed skipped"
fi

# ------------------------------------------------------------------ build ----

step "Building and starting the app"

# One retry: pulling the Dockerfile syntax image occasionally times out against
# the registry, and that failure is transient rather than a real build error.
if ! $COMPOSE up -d --build app; then
  warn "Build failed — retrying once in case it was a transient registry error"
  sleep 5
  $COMPOSE up -d --build app || die "Build failed twice.
  If the error was 'getaddrinfo ENOTFOUND postgres', the build ran on the wrong
  builder. Check that '$BUILDX_BUILDER' exists and is attached to the 'sustlabs'
  network:  docker buildx inspect $BUILDX_BUILDER"
fi

# ------------------------------------------------------------------ verify ---

step "Verifying"

CODE=""
i=0
while [ $i -lt 30 ]; do
  CODE=$(curl -s -o /dev/null -w '%{http_code}' --max-time 5 "http://127.0.0.1:$HOST_PORT/" 2>/dev/null || true)
  [ "$CODE" = "200" ] && break
  i=$((i + 1))
  sleep 2
done

if [ "$CODE" != "200" ]; then
  $COMPOSE logs --tail 30 app || true
  die "The app did not start responding on port $HOST_PORT. Logs are above."
fi

ok "Site responding (HTTP 200)"
ok "Admin: $(curl -s -o /dev/null -w '%{http_code}' --max-time 10 "http://127.0.0.1:$HOST_PORT/admin" || echo '?')"

printf '\n%sReady.%s\n' "$G$B" "$X"
printf '  Site   http://localhost:%s\n' "$HOST_PORT"
printf '  Admin  http://localhost:%s/admin\n\n' "$HOST_PORT"
printf '  Logs   make logs\n'
printf '  Stop   make stop\n'
printf '  More   make help\n\n'
